### ISSUE TITLE
Ruby `Enumerable#sum` doesn't work properly with `Length` objects

### ISSUE THREAD

**Issue by maxp-hover** [SketchUp/api-issue-tracker#1024]
I have tested on Sketchup 2023 and 2024 on ARM Mac

The issue is simple to reproduce. Create a few edges, select them, then run the following code snippets in console:

```
Sketchup.active_model.selection.sum(&:length)
```

```
Sketchup.active_model.selection.map(&:length).sum
```

Only the second returns the correct result. The first just returns the length of the first edge in the selection. 

I opened a forum post about this here a few years ago here, but didn't make a bug report for it. https://forums.sketchup.com/t/sketchup-selection-sum-doesnt-work-properly/187279

This is a really easy thing for a plugin / API developer to miss. Imagine someone is writing totally valid ruby code (for pretty much basic arithmetic) and it returns the wrong value. Clearly there are workarounds, but it's one of those things which can very easily slip under the radar and cause woe for the developer to figure out what's happening.

**Comment by thomthom** [comment]
Interesting... Wonder why...

`Length` has always been a troublesome type... Ruby doesn't really let you subclass `Float`. In the old days it was done by monkeypatching some internal pointers in the Ruby data object. In a later Ruby release that broke and we had to apply some nasty shims. I bet this relates to this issue.

**Comment by MSP-Greg** [comment]
I think this is a Ruby bug/quirk.  I should be posting a bug report with Ruby shortly.  Or, I can repro it using stand-alone Ruby, and I was using Ruby master built today...

**Comment by thomthom** [comment]
Thanks for digging up that bug Greg! I'll add a note internally that there's a bugfix in Ruby to pick up.

**Comment by MSP-Greg** [comment]
You're welcome.

JFYI, I looked at the code in [Enumerable#sum](https://msp-greg.github.io/ruby_trunk/Core/Enumerable.html#sum-instance_method) and [Array#sum](https://msp-greg.github.io/ruby_trunk/Core/Array.html#sum-instance_method), and they weren't quite the same.  Ruby core has several very good c coders, so I created the simple Ruby code showing the problem, and it was fixed quickly.

Re the subclass issue, I recall years ago that another language differentiated between 'primitive' objects and 'regular' objects.  Primitive objects were always passed by value.  Regular objects were passed by reference.

Most (all?) of Ruby's numeric classes are primitive, and so subclassing them is very messy, especially because operations on them return a superclass object, not a subclass object...

**Comment by thomthom** [comment]
> Most (all?) of Ruby's numeric classes are primitive, and so subclassing them is very messy, especially because operations on them return a superclass object, not a subclass object...

Yea, Length should never have been a subclass of Float. It should have had a float as a member.

In Ruby integers (except BigInts) are immediate values. Float kindof to... but still have a data structure (if I recall correctly last time I checked. Though, very much an implementation detail). I'm seeing the same in Python as well.
